In [1]:
import numpy as np


In [4]:
#Array vs List
l1=['naushad',67,True,56.9]
print(l1)

['naushad', 67, True, 56.9]


In [5]:
arr1=['na','halo']
print(arr1)

['na', 'halo']


In [6]:
#Array occupies less memory and is fast ie more convinient to use
#we can create using two method:using array module and using numpy. 

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [17]:
arr2=np.array([1,3,4,5],"float",ndmin=3)
print(arr2)

[[[1. 3. 4. 5.]]]


In [11]:
arr3=np.array([[1,2,3],[3,4,5]])
arr3

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
#arange function
#array creation routines based on the numerical ranges.creates instance of ndarray with evenly space values and returns 
#the reference to it.

In [20]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [21]:
arr3=np.array(np.arange(3,9,2),"float",ndmin=2)
arr3

array([[3., 5., 7.]])

In [23]:
arr0=np.arange(3,9,2)
arr0

array([3, 5, 7])

In [26]:
print(type(arr3))
print(type(arr0))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
#help(np.empty)

In [31]:
a0=np.zeros(6,dtype='int')
a0

array([0, 0, 0, 0, 0, 0])

In [33]:
a1=np.ones((2,3),"float")
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
ae=np.empty(4,"int")
ae

array([-1431130594,  1037910237,  -967461357,   385901984])

In [37]:
#linspace:evenly spaced value over a specified interval
#similar to arange but here we can specifies the no. of samples btw the interval

In [78]:
#help(np.linspace)

In [65]:
my_lin=np.linspace(1,5,5,endpoint=False,retstep=True)
my_lin

(array([1. , 1.8, 2.6, 3.4, 4.2]), 0.8)

In [73]:
my_lin1=np.linspace(1,5,5,endpoint=True,retstep=True,dtype="int")
my_lin1

(array([1, 2, 3, 4, 5]), 1.0)

In [76]:
print(type(my_lin1))

<class 'tuple'>


In [79]:
my_lin=np.linspace(1,5,5)
my_lin

array([1., 2., 3., 4., 5.])

In [81]:
#Identity func:=square array with one on the main diagonal.
#Eye func: Returns 2d array with 1's as the diagoanal and 0's elsewhere

In [93]:
'''arrId=np.eye(4,5,0,dtype="int")
arrId
output:
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])'''

e=np.eye(4,5,-2,dtype="int")
e
#two pos downward due to negative k value

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [94]:
print(type(e))

<class 'numpy.ndarray'>


In [96]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            The ``like`` keyword is an experimental feature pending on
            acceptance of :ref:`NEP 35 <NEP35>`.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` 

In [97]:
i=np.identity(4,"complex")
i

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [98]:
#attributes of array

In [110]:
a=np.arange(1,6,2,dtype="float")
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[1. 3. 5.]
1
(3,)
float64
8


In [117]:
#Indexing/slicing in array
b=np.array([[1,2,3],[2,3,4,8,9]])
b
print(b[0])
print(b[1][0:5:2])

[1, 2, 3]
[2, 4, 9]


<ipython-input-117-7551362371b1>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[2,3,4,8,9]])


In [121]:
a=np.arange(1,6,2,dtype="int")
print(a**2)


[ 1  9 25]


In [124]:
#Reshape and resize
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [125]:
arr4=np.array(np.arange(3,9,),"float",ndmin=2)
arr4

array([[3., 4., 5., 6., 7., 8.]])

In [127]:
c=np.reshape(arr4,(2,3))
c

array([[3., 4., 5.],
       [6., 7., 8.]])

In [134]:
print(np.reshape(c,(3,2),order="C"))
print(np.reshape(c,(3,2),order="F"))
print(np.reshape(c,(3,2),order="A"))
print(np.reshape(c,(3,2)))

[[3. 4.]
 [5. 6.]
 [7. 8.]]
[[3. 7.]
 [6. 5.]
 [4. 8.]]
[[3. 4.]
 [5. 6.]
 [7. 8.]]
[[3. 4.]
 [5. 6.]
 [7. 8.]]
